// Generated by CoffeeScript 1.9.3
(function() {
  ({
    mergefile: "file1.mustache",
    view: {
      technology: "ios",
      content2: "welcome to the ios vehicle observers, it's a bit different than other..."
    }
  });

}).call(this);

//# sourceMappingURL=000_vehicle_observers.js.map
